<?php
session_start();
//security k1
require_once("welcome.php");

$resetidX=mysqli_real_escape_string($con,$_POST['resetid']);
$sql=mysqli_query($con,"select name,email from allmember where email='$resetidX'");
if(mysqli_num_rows($sql)==1)
{
	while($row=mysqli_fetch_assoc($sql))
	{
		$random_password=str_shuffle("1234567890");
                             $conformation_code_reset=substr($random_password,0,8);
                             $_SESSION["conformation_code_reset"]=$conformation_code_reset;
		                     $emailX=$row['email']; 
							 $nameX=$row['name'];
		                     $to   = $emailX;
                             $from = 'noreply@nightbird.in';
                             $headers = "From:Night Bird \r\n";
                             $headers .= "CC: noreply@nightbird.com\r\n";
                             $headers .= 'MIME-Version: 1.0' . "\r\n";
                             $headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";
  
                             $message = '<html><body>';
 
                             $message .= '<table width="100%"; rules="all"  cellpadding="10">';
 
                             $message .= "<tr><td><img src='http://nightbird.in/img/nightlogo.png' height='150px'alt='Night Bird' /></td></tr>";
 
                             $message .= "<tr><td colspan=2>Dear  $nameX , we have received a password change request from your account.<br /><br />.</td></tr>";
 
                             $message .= "<tr><td colspan=2 font='colr:#999999;'><I>Your verification code is $conformation_code_reset</I></td></tr>"; 
                             $message .= "<tr><td colspan=2 ><I>If this conformation code is not generated by you then <a href=''>Click Here</a></I></td></tr>";
                             $message .= "</table>";
 
                             $message .= "</body></html>";
	                         $subject="Verification Code";	
                             $ip_address = $_SERVER['REMOTE_ADDR'];
                             $browser = $_SERVER['HTTP_USER_AGENT'];	
                             date_default_timezone_set('Asia/Calcutta');
   		                     if(mail($to, $subject, $message, $headers))
							 {
							echo $nameX;
								 
							 }
							 
	}
}
else
{
	echo 1;
}
?>